### ISSUE TITLE
404 on calls to update AccountLinking

### ISSUE THREAD

**Issue by gberk** [stoiveyp/Alexa.NET.Management#50]
It looks like the [EnumMember] attribute on the SkillStage enum is intended to serialize the values to lowercase as required by Alexa, but the string is getting cased like the declared value of the enum. (So for example the route includes /stages/Development rather than /stages/development) This is causing an incorrectly cased API route and leading to a 404.

**Comment by stoiveyp** [comment]
@gberk SkillStage in the url is handled by ManagementRefitSettings, and it turns out a few of the services covered by the package weren't referencing them, Account Linking was one such service.

I've updated all the services missing this requirement, added a test for account linking to ensure it doesn't revert, and the fix is in v3.0.4 which has just been published.
